config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  post 'pages/search' => 'pages#search', as: :search
  get 'pages/:id/detail' => 'pages#detail', as: :detail
  get 'pages/:id/confirm' => 'pages#confirm', as: :confirm
  get 'pages/contact' => 'pages#contact', as: :contact
  get 'tags/:tag' => 'pages#home', as: :tag
  get 'admin/tags/:tag' => 'admin/accounts#index', as: :admin_tag
  post 'express_checkout/:account_id', to: 'billing#express_checkout', as: :express_checkout
  get 'confirm_buy/:account_id', to: 'billing#confirm_buy', as: :confirm_buy
  post 'buy', to: 'billing#buy', as: :buy

  namespace :admin do
    root 'accounts#index'
    resources :account_photos
    resources :accounts

    resources :user_sessions
    resources :users

    get 'login' => 'user_sessions#new', :as => :login
    post 'logout' => 'user_sessions#destroy', :as => :logout
  end 

end

app/models/account.rb
class Account < ActiveRecord::Base
	has_many :photos, class_name: 'AccountPhoto', dependent: :destroy
	has_many :videos, dependent: :destroy
	accepts_nested_attributes_for :videos
	accepts_nested_attributes_for :photos
	scope :sellable, -> {where(selled: false)}

	acts_as_taggable
end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < Admin::BaseController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_filter :require_login

  # GET /accounts
  # GET /accounts.json
  def index
    if params[:tag]
      @accounts = Account.tagged_with(params[:tag])
    else
      @accounts = Account.all
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account_photos = @account.photos.all
  end

  # GET /accounts/new
  def new
    @account = Account.new
    @acc_photo = @account.photos.build
    @video = @account.videos.build
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        set_default = 0
        params[:acc_photos]['photo'].each do |a|
          @acc_photo = @account.photos.create!(:photo => a, :account_id => @account.id)
          @acc_photo.save
        end
        format.html { redirect_to [:admin, :accounts], notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        if params[:acc_photos]
          params[:acc_photos]['photo'].each do |a|
            @acc_photo = @account.photos.create!(:photo => a, :account_id => @account.id)
          end
        end 
        format.html { redirect_to [:admin, :accounts], notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    img_del = AccountPhoto.where("account_id = ?", @account.id)
    img_del.each do |d|
      d.destroy
      d.save
    end
    @account.destroy
    respond_to do |format|
      format.html { redirect_to [:admin, :accounts], notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:lv, :price, :description, :video, :selled, :user, :pass, :name, :tag_list ,photos_attributes:[:id, :account_id, :photo], videos_attributes:[:id, :video, :account_id])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/admin/accounts/_form.html.erb
<%= nested_form_for([:admin,@account]) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lv %><br>
    <%= f.number_field :lv %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :selled %><br>
    <%= f.check_box :selled %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :pass %><br>
    <%= f.text_field :pass %>
  </div>

  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>

  <div>
  <%= f.label :video %>
  <%= f.fields_for :videos do |v| %>
    <%= v.text_field :video %>
    <%= v.link_to_remove 'remove' %>
  <% end %>
  <p><%= f.link_to_add "add", :videos %></p>
  </div>

  <%= f.fields_for :acc_photos do |p| %>
    <div class="field">
     <%= p.label :photo %><br>
     <%= p.file_field :photo, :multiple => true, name: "acc_photos[photo][]" %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script type="text/javascript">
$( document ).ready(function() {
  $(".menu").removeClass("active");
  $("#Account").addClass("active");
});
</script>

app/views/admin/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin,@account] %> |
<%= link_to 'Back', admin_accounts_path %>

app/views/admin/accounts/index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Lv</th>
      <th>Price</th>
      <th>Description</th>
      <th>Selled</th>
      <th>Payer_id</th>
      <th>Payer_ip</th>
      <th>Payer_email</th>
      <th>Tag</th>
      <th colspan="3" style="text-align:center">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.lv %></td>
        <td><%= account.price %></td>
        <td><%= account.description %></td>
        <td><%= account.selled %></td>
        <td><%= account.payer_id %></td>
        <td><%= account.payer_ip %></td>
        <td><%= account.payer_email %></td>
        <td>Tags: <%= raw account.tag_list.map {|t| link_to t, admin_tag_path(t)}.join(',')%></td>
        <td><%= link_to 'Show', [:admin, account] %></td>
        <td><%= link_to 'Edit', [:edit, :admin, account] %></td>
        <td><%= link_to 'Destroy',[:admin, account], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_admin_account_path %>
<script type="text/javascript">
$( document ).ready(function() {
  $(".menu").removeClass("active");
  $("#Account").addClass("active");
});
</script>

app/views/admin/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_accounts_path %>

app/views/admin/accounts/show.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>
  <div class="col-md-6">
    <p>
      <strong>Lv:</strong>
      <%= @account.lv %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @account.price %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @account.description %>
    </p>
  </div>
  <div class="col-md-6">
    <p>
      <strong>Selled:</strong>
      <%= @account.selled %>
    </p>

    <p>
      <strong>User:</strong>
      <%= @account.user %>
    </p>

    <p>
      <strong>Pass:</strong>
      <%= @account.pass %>
    </p>
  </div>
  
  <div class="col-md-9">
    <p>
      <% @account.videos.all.each do |v| %>
        <strong>Video:</strong>
        <%= v.video %>
      <% end %>
    </p>
  </div>

  <div class="col-md-3">
    <%= link_to 'Edit', [:edit, :admin, @account], class:"btn btn-primary", role:"button"%> 
    <%= link_to 'Back', admin_accounts_path, class:"btn btn-primary", role:"button"%>
  </div>
  
  <div class="col-md-12"></div>

  <% @account_photos.each do |account_photo| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= image_tag account_photo.photo_url , class: "img-rounded", style:"width: 200px; height: 200px;" %>
        <div class="caption">
          <p><%= link_to 'delete image',[:admin, account_photo], method: :delete, class:"btn btn-primary", role:"button", data: { confirm: 'Are you sure?' }%></p>
        </div>
      </div>
    </div>
  <% end %>

  <script type="text/javascript">
  $( document ).ready(function() {
    $(".menu").removeClass("active");
    $("#Account").addClass("active");
  });
  </script>
</div>