config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  post 'pages/search' => 'pages#search', as: :search
  get 'pages/:id/detail' => 'pages#detail', as: :detail
  get 'pages/:id/confirm' => 'pages#confirm', as: :confirm
  get 'pages/contact' => 'pages#contact', as: :contact
  get 'tags/:tag' => 'pages#home', as: :tag
  get 'admin/tags/:tag' => 'admin/accounts#index', as: :admin_tag
  post 'express_checkout/:account_id', to: 'billing#express_checkout', as: :express_checkout
  get 'confirm_buy/:account_id', to: 'billing#confirm_buy', as: :confirm_buy
  post 'buy', to: 'billing#buy', as: :buy

  namespace :admin do
    root 'accounts#index'
    resources :account_photos
    resources :accounts

    resources :user_sessions
    resources :users

    get 'login' => 'user_sessions#new', :as => :login
    post 'logout' => 'user_sessions#destroy', :as => :logout
  end 

end

app/views/pages/confirm.html.erb
<div class='row'>
	<div class='col-md-12'>
		<p><h2 style="text-align:center">Terms And Conditions</h2></p>
		<div class="highlight">
			<pre>
				<code class="html">
					<span class="nt">ljshdsuehkughlireuhgehrghsvekngjwlerkjgwlcevhfgikjgjvntvgjnrntuvbgnhrhfgbcwienhfcfdosjrnfkln</span>
					<span class="nt">ljshdfdosjrnfkln</span>
				</code>
			</pre>
		</div>
		<div class="checkbox">
		  <label>
		    <input id="terms" type="checkbox" value="">
		    I agree with this terms and conditions
		  </label>
		</div>
		<p id="paypal" style="text-align:center; display:none ">
		  <%= link_to express_checkout_path(account_id: params[:id]), method: :post do %>
		  	<%= image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif") %>
		  <% end %>
		</p>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('#terms').on('click', function() {
			if($('#terms').is(':checked')) {
				$('#paypal').show();
			} 
			else {
			$('#paypal').hide();
			}
		})
	})
</script>

app/views/pages/contact.html.erb
admin@email.com

<script type="text/javascript">
$( document ).ready(function() {
  $(".menu").removeClass("active");
  $("#Contact").addClass("active");
});
</script>

app/views/pages/detail.html.erb
<div class="row">

	<div class="col-md-5">
		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
			<ol class="carousel-indicators">
				<% index = 0 %>
				<% @account.photos.all.count.times do |num| %>
				<li data-target="#carousel-example-generic" data-slide-to="<%= num %>" class="<%= index == 0 ? 'active' : ''%>"></li>
				<% index += 1 %>
				<% end %>
			</ol>
			<div class="carousel-inner">
				<% @account.photos.all.each_with_index do |a, index| %>
				<div class="item <%= index == 0 ? 'active' : '' %>">
					<%= image_tag a.photo_url %>
				</div>
				<% end %>
			</div>
			<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
				<span class="glyphicon glyphicon-chevron-left"></span>
			</a>
			<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
				<span class="glyphicon glyphicon-chevron-right"></span>
			</a>
		</div>
		<p><h2 style="text-align: center"><%= number_to_currency @account.price ,unit: '$', precision: 0%></h2></p>
		<%= link_to 'Buy Now', confirm_path(id: @account), class: "btn btn-block btn-primary", role: "button", style: "margin: 20px auto 0px auto"%>
	</div>


	<div class="col-md-7">
		<div class="bs-example bs-example-tabs">
	    <ul id="myTab" class="nav nav-tabs" role="tablist">
	      <li class="active"><a href="#detail" role="tab" data-toggle="tab">Detail</a></li>
	      <li><a href="#video" role="tab" data-toggle="tab">Video</a></li>
	    </ul>

	    <div id="myTabContent" class="tab-content" style="margin: 10px" >
	      <div class="tab-pane fade in active" id="detail">
	      	<h1>Level:<%= @account.lv%></h1>
	      	<p><%= @account.description %></p>
	      	<p>Tag: <%= raw @account.tag_list.map {|t| link_to t, tag_path(t)}.join(',') %></p>
					<!--<p><%#= @account.attributes.each{|key,value| "#{key}:#{value}"} %></p>-->
	      </div>

	      <div class="tab-pane fade" id="video">
	      	<div class="bs-example">
				    <!--<div class="embed-responsive embed-responsive-16by9">
				    	<iframe width="560" height="315" src="//www.youtube.com/embed/<%= @account.videos.first %>" frameborder="0" allowfullscreen></iframe>
				    </div>-->

				    <div id="carousel-video-generic" class="carousel slide" data-ride="carousel">
							<ol class="carousel-indicators">
								<% index = 0 %>
								<% @account.videos.all.count.times do |num| %>
								<li data-target="#carousel-video-generic" data-slide-to="<%= num %>" class="<%= index == 0 ? 'active' : ''%>"></li>
								<% index += 1 %>
								<% end %>
							</ol>
							<div class="carousel-inner">
								<% @account.videos.all.each_with_index do |a, index| %>
								<div class="item <%= index == 0 ? 'active' : '' %>">
									<div class="embed-responsive embed-responsive-16by9">
							    	<iframe width="560" height="315" src="//www.youtube.com/embed/<%= a.video %>" frameborder="0" allowfullscreen></iframe>
							    </div>
								</div>
								<% end %>
							</div>
							<a class="left carousel-control" href="#carousel-video-generic" role="button" data-slide="prev">
								<span class="glyphicon glyphicon-chevron-left"></span>
							</a>
							<a class="right carousel-control" href="#carousel-video-generic" role="button" data-slide="next">
								<span class="glyphicon glyphicon-chevron-right"></span>
							</a>
						</div>
				  </div>
	      </div>
			</div>
  	</div>
	</div>

</div>
<script type="text/javascript">
$(document).ready(function(){
  <% b=[] %>
  <% Tags.all.each do |t| b.push(t.name) end %>
  var tags = [];
  tags = <%= raw b %>
  $('#search').typeahead({source: tags});
});
</script>

app/views/pages/home.html.erb
<div class="row">
	<% @accounts.each do |a| %>
	  <div class="col-md-3">
	    <div class="thumbnail">
				<% img = a.photos.first %>
				<%= link_to detail_path(id: a)  do %> 
					<%= image_tag img.photo_url,style: "height: 100%; width: 100%; display: block "%>
				<% end %>
	      <div class="caption">
	        <h3>Level <%= a.lv %></h3>
	        <p style="overflow:hidden"><%= a.description %></p>
	        <p><%= link_to 'Buy Now', confirm_path(id: a), class: "btn btn-block btn-primary", role: "button"%></p>
	      </div>
	    </div>
	  </div>
	<% end %>
</div>
<script type="text/javascript">
$(document).ready(function(){
  <% b=[] %>
  <% Tags.all.each do |t| b.push(t.name) end %>
  var tags = [];
  tags = <%= raw b %>
  $('#search').typeahead({source: tags});
});
</script>

app/views/pages/search.html.erb
<div class="row">
	<% @accs.each do |a| %>
		<div class="col-md-3">
			<div class="thumbnail">
				<% acc = Account.find(a) %>
				<% img = acc.photos.first %>
				<%= link_to detail_path(acc) do %>
					<%= image_tag img.photo_url,style: "height: 100%; width: 100%; display: block " %>
				<% end %>
			
				<div class="caption">
					<h3>Level <%= acc.lv %></h3>
					<p><%= acc.description %></p>
					<p style="text-align:center"><%= link_to 'Buy Now', confirm_path(id: a), class: "btn btn-block btn-primary", role: "button"%></p>
				</div>
			</div>
		</div>
	<% end %>
</div>