config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  post 'pages/search' => 'pages#search', as: :search
  get 'pages/:id/detail' => 'pages#detail', as: :detail
  get 'pages/:id/confirm' => 'pages#confirm', as: :confirm
  get 'pages/contact' => 'pages#contact', as: :contact
  get 'tags/:tag' => 'pages#home', as: :tag
  get 'admin/tags/:tag' => 'admin/accounts#index', as: :admin_tag
  post 'express_checkout/:account_id', to: 'billing#express_checkout', as: :express_checkout
  get 'confirm_buy/:account_id', to: 'billing#confirm_buy', as: :confirm_buy
  post 'buy', to: 'billing#buy', as: :buy

  namespace :admin do
    root 'accounts#index'
    resources :account_photos
    resources :accounts

    resources :user_sessions
    resources :users

    get 'login' => 'user_sessions#new', :as => :login
    post 'logout' => 'user_sessions#destroy', :as => :logout
  end 

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password_confirmation
	authenticates_with_sorcery!
end

app/controllers/admin/users_controller.rb
class Admin::UsersController <  Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:index, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to [:admin, @users], notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
$( document ).ready(function() {
  $(".menu").removeClass("active");
  $("#User").addClass("active");
});
</script>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @user] %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3" style="text-align:center">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Edit', [:edit, :admin, user] %></td>
        <td><%= link_to 'Destroy', [:admin, user], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path %>

<script type="text/javascript">
$( document ).ready(function() {
  $(".menu").removeClass("active");
  $("#User").addClass("active");
});
</script>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_login_path %>