config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  post 'pages/search' => 'pages#search', as: :search
  get 'pages/:id/detail' => 'pages#detail', as: :detail
  get 'pages/:id/confirm' => 'pages#confirm', as: :confirm
  get 'pages/contact' => 'pages#contact', as: :contact
  get 'tags/:tag' => 'pages#home', as: :tag
  get 'admin/tags/:tag' => 'admin/accounts#index', as: :admin_tag
  post 'express_checkout/:account_id', to: 'billing#express_checkout', as: :express_checkout
  get 'confirm_buy/:account_id', to: 'billing#confirm_buy', as: :confirm_buy
  post 'buy', to: 'billing#buy', as: :buy

  namespace :admin do
    root 'accounts#index'
    resources :account_photos
    resources :accounts

    resources :user_sessions
    resources :users

    get 'login' => 'user_sessions#new', :as => :login
    post 'logout' => 'user_sessions#destroy', :as => :logout
  end 

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwTrade</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<style type="text/css">
.typeahead{
  width: 76.2em
}
</style>
<div class="container">

  <div class="masthead">
    <ul class="nav nav-justified">
      <li class="menu" id="Account"><%= link_to 'Account', admin_root_path %></li>
      <li class="menu" id="User"><%= link_to 'User', admin_users_path %></li>
      <li class="menu"><a href="#">Blank</a></li>
      <li class="menu"><a href="#">Blank</a></li>
      <li class="menu"><a href="#">Blank</a></li>
      <li class="menu"><%= link_to 'Home', root_path %></li>
    </ul>
  </div>
  
  
  <% flash.each do |type, message| %>
    <div class="alert alert-warning" role="alert">
      <%= message %>
    </div>
  <% end %>

  <div>
    <% if current_user %>
      <%= link_to 'log out',admin_logout_path, method: :post %>
    <% end %>
  </div>

  <%= yield %>

  <!-- Site footer -->
  <div class="footer">
    <p>© Company 2014</p>
  </div>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwTrade</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<style type="text/css">
.typeahead{
  width: 76.2em
}
</style>
<div class="container">

  <div class="masthead">
    <ul class="nav nav-justified">
      <li class="menu active" id="Home"><%= link_to 'Home', root_path %></li>
      <li class="menu"><a href="#">Projects</a></li>
      <li class="menu"><a href="#">Services</a></li>
      <li class="menu"><a href="#">Downloads</a></li>
      <li class="menu"><a href="#">About</a></li>
      <li class="menu" id="Contact"><%= link_to 'Contact', contact_path %></li>
    </ul>
  </div>
  <div style="margin-top: 2em; margin-bottom: 1em">
    <%= form_tag search_path, :method => 'post', role: "form", class: "form-inline" do %>
      <%= text_field_tag :search, params[:search], class: "form-control ", id: "search", autocomplete: "off",placeholder: "Search Monster Here", style: "width:75.9em", autocomplete: 'off', :data => {:provide => "typeahead"} %>
      <!--<input type="text" data-provide="typeahead" id="search" autocomplete="off">-->
      <%= submit_tag "search", :name => :nil, class: "btn btn-default"%>
    <% end %>
  </div>

  <% flash.each do |type, message| %>
    <div class="alert alert-warning" role="alert">
      <%= message %>
    </div>
  <% end %>

  <!-- Example row of columns -->
  <!--<div class="row">
    <div class="col-lg-4">
    </div>
  </div>-->
  <%= yield %>

  <!-- Site footer -->
  <div class="footer">
    <p>© Company 2014</p>
  </div>
</div>

</body>
</html>